### ISSUE TITLE
Confusion over installing paper-card

### ISSUE THREAD

**Issue by samuelli** [andytuwm/paper-card#4]
Hi,

Given that this repo is 2 years out of date, do you think it would be possible for you to unpublish this from the bower registry? This is causing confusion to some of our users.

Thanks,
Sam

**Comment by andytuwm** [comment]
Done! thanks for letting me know, it was a learning experience from when i first started doing frontend.

Apologies for registering a name that would've reasonably been chosen when there wasn't a 'paper-card' component! It should be unregistered now.

**Comment by samuelli** [comment]
Thanks!
